channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.2.2
- pip:
  - mlflow==2.5.0
  - cloudpickle==2.0.0
  - configparser==5.2.0
  - flask==3.0.0
  - psutil==5.9.0
  - scikit-learn==1.1.1
  - typing-extensions==4.3.0
name: mlflow-env
